VNA_IP = "TCPIP0::192.168.0.144::inst0::INSTR"
VNA_TIMEOUT_MS = 60 * 60 * 1000
SG_IP = "TCPIP0::192.168.0.140::inst0::INSTR"
SG_VNA_WAIT_TIME = 0.01

LABBER_SERVER = "localhost"
LABBER_SERVER_TIMEOUT = None # We are not using Labber. The name is for legacy compatibility 
ATTENUATOR_NAME = "Painter Vaunix Lab Brick Digital Attenuator"
ATTENUATOR_INTERFACE = "GPIB"
ATTENUATOR_ADDRESS = "28835"
ATTENUATOR_WAIT_S = 2

SG_NAME = "Zurich Instruments HDAWG"
SG_INTERFACE = "TCPIP"
SG_ADDRESS = "192.168.0.140"
SG_MAX_POWER = 0


TRANSMISSION_COUPLED = False
PRIOR_F0 = 6.1627e9
PRIOR_KAPPA = 0.1e6


NAIVE = True
VNA_START_FREQ = None
VNA_STOP_FREQ = None
VNA_CENTER_FREQ = PRIOR_F0
VNA_SPAN_FREQ = PRIOR_KAPPA * 100
VNA_COARSE_SWEEP_POINTS = 101
VNA_DENSE_SWEEP_POINTS = 101
VNA_ADAPTIVE_SWEEP_POINTS = 2 + 25
VNA_ADAPTIVE_ITERATIONS = 3
VNA_POWER_DBM = 0; assert VNA_POWER_DBM <= 0
VNA_IFBW = 1_000
# VNA_LIST_OF_AVERAGES = [10, 10, 10, 20, 20, 20, 50, 100, 200, 500, 1000]
VNA_LIST_OF_AVERAGES = [50]
# ATTENUATOR_ATTENUATIONS = [i for i in range(0, 55, 5)]; assert all(attenuation >= 0 for attenuation in ATTENUATOR_ATTENUATIONS); assert len(VNA_LIST_OF_AVERAGES) == len(ATTENUATOR_ATTENUATIONS)
ATTENUATOR_ATTENUATIONS = [30]; assert all(attenuation >= 0 for attenuation in ATTENUATOR_ATTENUATIONS); assert len(VNA_LIST_OF_AVERAGES) == len(ATTENUATOR_ATTENUATIONS)


NAIVE = True
VNA_POWER_DBM = 0; assert VNA_POWER_DBM <= 0
VNA_IFBW = 1000
VNA_AVERAGES = 500

SG_START_FREQ = 0.8e9
SG_STOP_FREQ = 1.3e9
SG_COARSE_SWEEP_POINTS = 9
SG_DENSE_SWEEP_POINTS = 401
SG_ADAPTIVE_SWEEP_POINTS = 2 + 51
SG_ADAPTIVE_ITERATIONS = 4
SG_MAX_ALLOWED_POWER = 1
SG_POWERS = [-5,]; assert all(power < 1 for power in SG_POWERS)
THRESHOLD_KAPPA_MULTIPLIER = 1.20