import config

TRANSMISSION_COUPLED = config.TRANSMISSION_COUPLED
PRIOR_F0 = config.PRIOR_F0
PRIOR_KAPPA = config.PRIOR_KAPPA
TARGET_F0 = None

GENERATE_NEW_FREQS_EPSILON = 1e-6
GENERATE_NEW_FREQS_UPPER_LIMIT = 1e10
GENERATE_NEW_FREQS_LOWER_LIMIT = 1e9
SCIPY_MAXFEV = 1e6
PLOT_POINTS = 1e3
